version: '3'

services:
  mongodb:
    image: 'docker.io/bitnami/mongodb'
    ports:
      - "27017:27017"
    environment:
      - MONGODB_USERNAME=daffy
      - MONGODB_PASSWORD=pass
      - MONGODB_DATABASE=jp
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
  app:
    build: .
    command: npm run dev
    ports:
      - 7771:7771
    volumes:
      - .:/app/
      - nodemodules:/app/node_modules
    links:
      - mongodb
    depends_on: 
      - mongodb

volumes:
  mongodb_data:
    driver: local
  nodemodules: {}